matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 autopoint libwxgtk3.0-dev libchm-dev
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" 

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - autopoint libwxgtk3.0-dev libchm-dev
      compiler: clang

    - os: osx 
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - chmlib
            - wxmac
          update: true

language: c++

before_install:
  - eval "PATH=${PATH}:/usr/local/opt/gettext/bin"
  - eval "${MATRIX_EVAL}"

script:
    ./bootstrap && ./configure && make
